---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: attendee-service-source
#- name: concourse-pipeline-samples
#- name: current-app-info

run:
  path: attendee-service-source/ci/tasks/update-routes
